"use client";

import { useRef } from "react";
import { ArrowRight, CheckCircle2, CircleHelp, FileUp, Scale, UploadCloud, XCircle } from "lucide-react";

import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Card, CardContent } from "../ui/card";
import { getSellerResponsePresentation } from "../../lib/seller-response-presentation.ts";
import type { SellerResponseDraft } from "../../lib/seller-response-input.ts";
import type { CaseState, LegalRecommendation, OfficialActionPlan as OfficialActionPlanData, SellerResponseAnalysis } from "../../types/qaitar.ts";
import { useLanguage } from "./language-provider";
import { OfficialActionPlan } from "./official-action-plan";

export function SellerResponse({ result, recommendation, plan, state, draft, onDraftChange, onModeChange, onAnalyze, onDemo, onMarkResolved, error }: { result: SellerResponseAnalysis | null; recommendation: LegalRecommendation | null; plan: OfficialActionPlanData | null; state: CaseState; draft: SellerResponseDraft; onDraftChange: (draft: SellerResponseDraft) => void; onModeChange: (mode: SellerResponseDraft["mode"]) => void; onAnalyze: () => void; onDemo: () => void; onMarkResolved: () => void; error: string | null }) {
  const { locale, messages } = useLanguage();
  const input = useRef<HTMLInputElement>(null);
  if (!result) return (
    <section className="px-4 py-7 sm:px-7 lg:px-10 lg:py-9"><div className="mx-auto max-w-3xl">
      <Badge variant="secondary" className="mb-4 rounded-full"><FileUp /> {messages.seller.stage}</Badge><h1 className="text-3xl font-bold tracking-[-.04em]">{messages.seller.title}</h1><p className="mt-2 text-muted-foreground">{messages.seller.add}</p>
      <div role="group" aria-label={messages.seller.title} className="mt-6 flex flex-wrap gap-2">{(["file", "text", "no_response"] as const).map((mode) => <Button key={mode} type="button" variant={draft.mode === mode ? "default" : "outline"} aria-pressed={draft.mode === mode} onClick={() => onModeChange(mode)} className="rounded-xl">{messages.seller.modes[mode]}</Button>)}</div>
      {draft.mode === "file" && <Card className="mt-5 rounded-[24px] border-dashed border-primary/25 bg-[linear-gradient(180deg,rgba(237,243,255,.65),rgba(255,255,255,.4))] py-0 shadow-[0_14px_38px_rgba(20,39,78,.06)]"><CardContent className="flex min-h-[240px] flex-col items-center justify-center p-7 text-center"><span className="grid size-14 place-items-center rounded-2xl bg-primary text-primary-foreground"><UploadCloud className="size-6" /></span>{draft.file ? <><p className="mt-4 font-semibold">{draft.file.name}</p><p className="mt-1 text-xs text-muted-foreground">{messages.seller.ready}</p></> : <><p className="mt-4 font-semibold">{messages.seller.upload}</p><p className="mt-1 text-sm text-muted-foreground">PDF, JPG, PNG, WEBP</p></>}<div className="mt-5 flex w-full max-w-sm flex-col justify-center gap-2 sm:flex-row"><Button type="button" onClick={() => input.current?.click()} variant="outline" className="h-11 flex-1 rounded-xl bg-white"><UploadCloud /> {draft.file ? messages.seller.replace : messages.seller.choose}</Button><Button type="button" onClick={onDemo} variant="ghost" className="h-11 flex-1 rounded-xl text-primary">{messages.seller.demo}</Button></div>{draft.file && <Button type="button" variant="ghost" onClick={() => { onDraftChange({ mode: "file", file: null }); if (input.current) input.current.value = ""; }} className="mt-2">{messages.seller.remove}</Button>}<input ref={input} type="file" className="sr-only" aria-label={messages.seller.choose} accept="application/pdf,image/jpeg,image/png,image/webp" onChange={(event) => { onDraftChange({ mode: "file", file: event.target.files?.[0] ?? null }); event.currentTarget.value = ""; }} /></CardContent></Card>}
      {draft.mode === "text" && <Card className="mt-5 rounded-[24px] py-0 shadow-none"><CardContent className="p-6"><label htmlFor="seller-response-text" className="text-sm font-semibold">{messages.seller.textLabel}</label><p className="mt-1 text-sm text-muted-foreground">{messages.seller.textHint}</p><textarea id="seller-response-text" value={draft.text} onChange={(event) => onDraftChange({ mode: "text", text: event.target.value })} placeholder={messages.seller.textPlaceholder} rows={9} maxLength={12_000} className="mt-3 w-full rounded-xl border border-input bg-background p-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" /></CardContent></Card>}
      {draft.mode === "no_response" && <Card className="mt-5 rounded-[24px] py-0 shadow-none"><CardContent className="space-y-4 p-6"><p className="text-sm text-muted-foreground">{messages.seller.noResponseHint}</p><label className="block text-sm font-semibold">{messages.seller.sentLabel}<input type="date" value={draft.claimSentAt} onChange={(event) => onDraftChange({ ...draft, claimSentAt: event.target.value })} className="mt-2 block h-11 w-full max-w-xs rounded-xl border border-input bg-background px-3" /></label><label className="block text-sm font-semibold">{messages.seller.receivedLabel}<input type="date" value={draft.claimReceivedAt} onChange={(event) => onDraftChange({ ...draft, claimReceivedAt: event.target.value })} className="mt-2 block h-11 w-full max-w-xs rounded-xl border border-input bg-background px-3" /></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={draft.receiptVerified} onChange={(event) => onDraftChange({ ...draft, receiptVerified: event.target.checked })} className="mt-1" /><span>{messages.seller.receiptVerification}</span></label><p className="text-sm text-muted-foreground">{messages.seller.receiptGuidance}</p></CardContent></Card>}
      {error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}
      <div className="mt-6 flex justify-end"><Button type="button" onClick={onAnalyze} size="lg" className="h-12 w-full rounded-xl sm:w-auto">{error ? messages.seller.retry : messages.seller.analyze} <ArrowRight /></Button></div>
    </div></section>
  );

  const presentation = getSellerResponsePresentation(result.responseType, locale);
  const badgeTone = {
    success: "bg-emerald-100 text-emerald-800",
    danger: "bg-rose-100 text-rose-800",
    notice: "bg-amber-100 text-amber-900",
  }[presentation.tone];
  const StatusIcon = presentation.tone === "success" ? CheckCircle2 : presentation.tone === "danger" ? XCircle : CircleHelp;
  return (
    <section className="px-4 py-7 sm:px-7 lg:px-10 lg:py-9"><div className="mx-auto max-w-[920px]">
      <Badge className={`mb-4 rounded-full ${badgeTone}`}><StatusIcon /> {presentation.label}</Badge><h1 className="text-3xl font-bold tracking-[-.04em]">{result.responseType === "no_response" ? messages.seller.noResponseReceived : messages.seller.received}</h1><p className="mt-2 text-sm text-muted-foreground">{result.responseType === "no_response" ? messages.seller.noResponseReceivedHint : messages.seller.receivedHint}</p>
      <div className="mt-7 grid gap-4 sm:grid-cols-2"><Card className="rounded-[22px] py-0 shadow-[0_10px_30px_rgba(20,39,78,.05)]"><CardContent className="p-6"><p className="text-xs font-bold uppercase tracking-[.1em] text-muted-foreground">{messages.seller.position}</p><p className="mt-3 text-lg font-semibold leading-7">{result.sellerReason ?? messages.seller.noReason}</p><p className="mt-4 text-sm leading-6 text-muted-foreground">{result.summary}</p></CardContent></Card><Card className="rounded-[22px] border-primary/20 bg-primary/[.045] py-0 shadow-none"><CardContent className="p-6"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-primary"><Scale className="size-4" /> {messages.seller.meaning}</div><p className="mt-3 text-base font-semibold leading-7">{recommendation?.summary ?? presentation.meaningFallback}</p></CardContent></Card></div>
      {recommendation && <Card className="mt-5 rounded-[24px] border-primary bg-primary text-primary-foreground py-0 shadow-[0_18px_42px_rgba(25,94,234,.22)]"><CardContent className="p-6 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.1em] text-primary-foreground/70">{messages.seller.next}</p><h2 className="mt-2 max-w-2xl text-2xl font-bold tracking-[-.03em]">{state === "ESCALATION_READY" ? presentation.nextTitle : messages.seller.nextTitle[result.responseType]}</h2><p className="mt-3 max-w-2xl text-sm font-medium leading-6">{recommendation.title}</p><p className="mt-2 max-w-2xl text-sm leading-6 text-primary-foreground/80">{recommendation.reasoning}</p></CardContent></Card>}
      {result.responseType === "accepted" && <Card className="mt-5 rounded-[24px] py-0 shadow-none"><CardContent className="p-6"><h2 className="text-lg font-semibold">{messages.seller.nextTitle.accepted}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{messages.seller.acceptedChecklist.map((item) => <li key={item}>{item}</li>)}</ul>{state === "RESOLVED" ? <p className="mt-4 text-sm font-semibold text-emerald-700">{messages.seller.resolvedDone}</p> : <Button type="button" className="mt-4 rounded-xl" onClick={onMarkResolved}>{messages.seller.resolved}</Button>}</CardContent></Card>}
      {result.responseType === "additional_information_requested" && <Card className="mt-5 rounded-[24px] py-0 shadow-none"><CardContent className="p-6"><h2 className="text-lg font-semibold">{messages.seller.requestedItems}</h2>{recommendation?.recommendedAction === "provide_document" && recommendation.missingInformation.length ? <ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{recommendation.missingInformation.map((item, index) => <li key={index}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">{result.summary || messages.seller.requestedFallback}</p>}</CardContent></Card>}
      {result.responseType === "unclear" && <Card className="mt-5 rounded-[24px] border-amber-300 bg-amber-50 py-0 shadow-none"><CardContent className="p-6 text-sm text-amber-950">{messages.seller.clarify}</CardContent></Card>}
      {(result.responseType === "rejected" || result.responseType === "no_response") && state === "ESCALATION_READY" && plan?.status === "ready" && <OfficialActionPlan plan={plan} />}
      {(result.responseType === "rejected" || result.responseType === "no_response") && (state !== "ESCALATION_READY" || plan?.status !== "ready") && <Card className="mt-5 rounded-[24px] border-amber-300 bg-amber-50 py-0 shadow-none"><CardContent className="p-6 text-amber-950"><h2 className="text-lg font-semibold">{messages.officialAction.manual}</h2><p className="mt-2 text-sm">{messages.seller.manualReview}</p>{plan?.missingInformation.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{plan.missingInformation.map((item, index) => <li key={index}>{item}</li>)}</ul> : null}</CardContent></Card>}
    </div></section>
  );
}
